# Generated by Django 5.0.3 on 2024-05-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='denomination',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='church',
            name='address',
        ),
        migrations.RemoveField(
            model_name='church',
            name='email',
        ),
        migrations.RemoveField(
            model_name='church',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='church',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=100),
        ),
    ]
