# Generated by Django 5.0.4 on 2024-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_denomination_church_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='church',
            name='location',
        ),
        migrations.AddField(
            model_name='church',
            name='address',
            field=models.CharField(default='Your default address here', max_length=255),
        ),
        migrations.AddField(
            model_name='church',
            name='denomination',
            field=models.CharField(default='Your default address here', max_length=100),
        ),
        migrations.AddField(
            model_name='church',
            name='email',
            field=models.EmailField(default='Your default address here', max_length=254),
        ),
        migrations.AddField(
            model_name='church',
            name='phone',
            field=models.CharField(default='Your default address here', max_length=15),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(default='Your default address here', max_length=100),
        ),
    ]
